# Generated by Django 5.1.2 on 2024-11-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('dob', models.DateField()),
                ('dor', models.DateField()),
                ('precinct', models.IntegerField()),
                ('party', models.TextField()),
                ('voter_score', models.IntegerField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apartment', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
