# Generated by Django 5.1.2 on 2024-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dor',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
