# Generated by Django 5.1.2 on 2024-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0006_alter_voter_dob_alter_voter_dor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.TextField(),
        ),
    ]
