# Generated by Django 5.1.2 on 2024-10-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_rename_image_file_image__file_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='_file',
            new_name='image_file',
        ),
    ]
